function makemex
%
% Function for generating gateway functions from MEX files for 
% SLICOT Basic Systems and Control Toolbox (Linux version, 64 bit).
% This file should be located in the directory containing the source MEX files, which is a subdirectory
% of the directory where the libraries slicot.a is located.

% Contributor:
% V. Sima, Jan. 2022.
%
% Revisions:
% -

flags = 'FFLAGS="$FFLAGS -fPIC -fno-omit-frame-pointer -fdefault-integer-8" -largeArrayDims';
mex_src = '';
files   = 'xerbla.f aux_sub.a';
libslicot = '../slicot.a';
%
slbasic_mex = {
  'arebench.f', ...
  'arecond.F', ...
  'aresol.f', ...
  'aresolc.f', ...
  'bldiag.F', ...
  'cfsys.F', ...
  'clsdp.f', ...
  'condis.F', ...
  'conhin.f', ...
  'datana.f', ...
  'deadbeat.F', ...
  'dishin.f', ...
  'dlsdp.f', ...
  'dlsdz.f', ...
  'fstoep.F', ...
  'fstoeq.f', ...
  'garesol.f', ...
  'genleq.f', ...
  'gsyscom.F', ...
  'gsystra.F', ...
  'HaeigZ.F', ...
  'Hamileig.f', ...
  'hapack_haeig.F', ...
  'Hessol.f', ...
  'Hnorm.F', ...
  'invert.F', ...
  'isprpr.F', ...
  'Kfiltupd.F', ...
  'ldsimt.f', ...
  'linmeq.f', ...
  'linorm.f', ...
  'mucomp.f', ...
  'muHopt.f', ...
  'perschur.F', ...
  'polass.f', ...
  'polezero.F', ...
  'polezeroz.F', ...
  'skewHamil2eig.F', ...
  'skewHamil2feig.F', ...
  'skewHamildefl.F', ...
  'skewHamildeflf.F', ...
  'skewHamildeflZ.F', ...
  'skewHamildeflfZ.F', ...
  'skewHamileig.F', ...
  'skewHamileigZ.F', ...
  'slmexp.F', ...
  'specfact.F', ...
  'symplURV.F', ...
  'symplURVZ.F', ...
  'syscf.f', ...
  'syscom.F', ...
  'sysconn.F', ...
  'sysfconn.F', ...
  'systra.f', ...
  'TotalLS.F', ...
     };
%
for k = 1:length(slbasic_mex)
    file = slbasic_mex{k};
    fprintf( 'mex %s %s%s %s %s -lmwlapack -lmwblas\n', flags, mex_src, file, files, libslicot );
    eval( sprintf( 'mex %s %s%s %s %s -lmwlapack -lmwblas\n', flags, mex_src, file, files, libslicot ) );
end
